config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/employees')
  resources :employees, except: [:show]
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validates :name, presence: true
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:edit, :update, :destroy]

  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to :employees, notice: 'Employee was successfully created.'
    else
      flash.now[:alert] = 'Employee could not be created - please check any errors and try again.'
      render :new
    end
  end

  def update
    if @employee.update(employee_params)
      redirect_to :employees, notice: 'Employee was successfully updated.'
    else
      flash.now[:alert] = 'Employee could not be updated - please check any errors and try again.'
      render :edit
    end
  end

  def destroy
    @employee.destroy
    redirect_to employees_url, notice: 'Employee was successfully deleted.'
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name, :title, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade in flash" role="alert">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">×</span><span class="sr-only">Close</span>
    </button>
    <p><%= flash[:alert] %></p>
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade in flash" role="alert">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">×</span><span class="sr-only">Close</span>
    </button>
    <p><%= flash[:notice] %></p>
  </div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="http://www.hrcomply.co.uk/" target="_blank">HRComply Demo</a>
    </div>
  </div>
</nav>

app/views/employees/_form.html.erb
<%= simple_form_for(@employee, html: { class: 'form-vertical' }) do |form| %>
  <%= form.input :name %>
  <%= form.input :title %>
  <%= form.input :notes, input_html: { rows: 6 } %>
  <%= form.submit class: 'btn btn-primary' %>
  <%= link_to 'Cancel', employees_path, class: 'btn btn-default' %>
<% end %>

app/views/employees/_notes.html.erb
<%= link_to '', '#', class: 'glyphicon glyphicon-info-sign', data: { toggle: 'modal', target: "#employee_notes_#{employee.id}" } %>
<%= content_tag :div, id: "employee_notes_#{employee.id}", class: 'modal fade' do %>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Employee Notes</h4>
      </div>
      <div class="modal-body">
        <% if employee.notes? %>
          <p><%= employee.notes %></p>
        <% else %>
          <p><em class="text-muted">There are no notes for <%= employee.name %></em></p>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= link_to 'Edit Notes', edit_employee_path(employee), class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class="page-header">
  <h2>Edit Employee</h2>
</div>

<%= render 'form' %>

app/views/employees/index.html.erb
<div class="page-header">
  <h2>Employees</h2>
</div>

<table class="table">
  <thead>
    <tr>
      <th width="5%">#</th>
      <th width="40%">Name</th>
      <th width="40%">Title</th>
      <th width="15%">&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% if @employees.empty? %>
      <tr>
        <td colspan="4">
          <em class="text-muted">There are no employees yet</em>
        </td>
      </tr>
    <% else %>
      <% @employees.each do |employee| %>
        <tr>
          <td>
            <%= employee.id %>
          </td>
          <td>
            <%= employee.name %>
            <%= render 'notes', employee: employee %>
          </td>
          <td>
            <%= employee.title %>
          </td>
          <td>
            <div class="actions text-nowrap pull-right">
              <%= link_to 'Edit', edit_employee_path(employee), class: 'btn btn-xs btn-primary' %>
              <%= link_to 'Delete', employee, class: 'btn btn-xs btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Employee', new_employee_path, class: 'btn btn-default' %>

app/views/employees/new.html.erb
<div class="page-header">
  <h2>New Employee</h2>
</div>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HRComply Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'navbar' %>
<div class="container-fluid">
  <%= render 'flash' %>
  <%= yield %>
</div>
</body>
</html>